### ISSUE TITLE
Add a way for players to select a single language at character creation

### ISSUE THREAD

**Issue by swissloaf** [terranova3/hl2rp-suggestions#13]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow players to choose from the list of languages at the character creation menu. Allow only one language to be selected per character. They then get the ability to speak and hear that language. TLDR: They get a single language option when creating a character.

**Describe alternatives you've considered**
None

**Additional context**
N/A Should be simple enough

**Comment by zacharyenriquee** [comment]
This is deliberate. We don't want language selection in character creation because it will become too accessible.
