### ISSUE TITLE
civil admins overall fixes 

### ISSUE THREAD

**Issue by speckyaus** [terranova3/hl2rp-suggestions#3]
**Is your feature request related to a problem? Please describe.**
Some of it. Scoreboard naming needs a fix, as provided in next question:

**Describe the solution you'd like**
Civil Administration to be granted access to:
/viewobjectives & /viewdata
Civil Administration to be autoset to "Administration" rather than "Administrator"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A.

**Comment by zacharyenriquee** [comment]
Completed for 1.2
