### ISSUE TITLE
Add blank books for people to write in

### ISSUE THREAD

**Issue by swissloaf** [terranova3/hl2rp-suggestions#5]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like for a new item to be made: a blank book. Similar to the notepad in writing, players can write in the book and title it as well. Possibly with pages too.

**Describe alternatives you've considered**
None

**Additional context**
It's literally not hard to imagine. It's like a notepad, but its model is a book and you can name it.

**Comment by zacharyenriquee** [comment]
This was added for the new update.
