### ISSUE TITLE
Teargas, Smoke grenade, Flashbang

### ISSUE THREAD

**Issue by syuzeren** [terranova3/hl2rp-suggestions#8]
**Is your feature request related to a problem? Please describe.**
Lack of ordinance use, plus very few less-than-lethal options available in roleplay.

**Describe the solution you'd like**
Teargas - applies low-tick damage effect just like toxic gas we use for QZ
Smoke - duh. creates thick, hard to see through effect
Flashbang - more difficult. also the one that is least necessary. creates a flash and a whine.

**Describe alternatives you've considered**
Could find an addon, but I know we are focused on custom scripts only.

**Additional context**
Doesn't need its own models. If it did have its own models, shit like CS:S ones would work fine for smoke and teargas and flash. If not get pouchy on it I guess.

**Comment by syuzeren** [comment]
Doesn't need its own models. If it did have its own models, shit like CS:S ones would work fine for smoke and teargas and flash. If not get pouchy on it I guess.

Would be super good to have. Most needed: teargas.

Teargas - applies low-tick damage effect just like toxic gas we use for QZ
Smoke - duh. creates thick, hard to see through effect
Flashbang - more difficult. also the one that is least necessary. creates a flash and a whine.

**Comment by zacharyenriquee** [comment]
Implemented
