### ISSUE TITLE
Nonlethal SPAS-12 (beanbag shotgun)

### ISSUE THREAD

**Issue by syuzeren** [terranova3/hl2rp-suggestions#9]
**Is your feature request related to a problem? Please describe.**
Need more less-than-lethal options.

**Describe the solution you'd like**
Add a beanbag shotgun / less-than-lethal shotgun that has the following effects:
- Barely any damage done when shot.
- Hollow sound effect when fired.
- Slows down those shot with the weapon.
- Ragdolls you if shot in the head.
- Pushes you back significantly when shot, like the shove feature.

**Describe alternatives you've considered**
Can just be an option selected in the C menu for regular SPAS-12 already in.

**Additional context**
Doesn't need its own model.

**Comment by paulp69** [comment]
> Beanbag shotgun.
> Either make it its own weapon (called it SPAS-12 Non-Lethal) or just make it an option to toggle when using the SPAS-12 so that it fires nonlethal rounds that shove people back or have the chance of ragdolling them if it hits their head. Maybe make it do like 1 damage per hit or something ridiculous.

I'd like to suggest that when the beanbag rounds hit a player they reduce the speed of the player.

**Comment by zacharyenriquee** [comment]
Was implemented.
